import { useEffect, useState } from 'react';
import { getInsights, analyzeCandidate, type AIInsight } from '../../api/ai';

export default function CandidateInsights({ candidateId }: { candidateId: string }) {
  const [insights, setInsights] = useState<AIInsight[]>([]);
  const [loading, setLoading] = useState(true);
  const [analyzing, setAnalyzing] = useState(false);

  useEffect(() => {
    loadInsights();
  }, [candidateId]);

  const loadInsights = () => {
    setLoading(true);
    getInsights(candidateId)
      .then(setInsights)
      .catch(console.error)
      .finally(() => setLoading(false));
  };

  const handleAnalyze = async () => {
    setAnalyzing(true);
    try {
      await analyzeCandidate(candidateId);
      loadInsights();
    } catch (err) {
      console.error(err);
    } finally {
      setAnalyzing(false);
    }
  };

  if (loading) return <div className="text-sm font-sans opacity-60">Loading AI insights...</div>;

  const latestInsight = insights[0];

  return (
    <div className="border border-rule bg-paper p-6 mt-8">
      <div className="flex justify-between items-center mb-4 pb-2 border-b border-rule">
        <h3 className="font-serif text-xl text-ink">AI Analysis</h3>
        <button 
          onClick={handleAnalyze} 
          disabled={analyzing}
          className="text-xs font-sans px-3 py-1 border border-rule hover:bg-rule/10 disabled:opacity-50"
        >
          {analyzing ? 'Analyzing...' : (latestInsight ? 'Refresh Analysis' : 'Run Analysis')}
        </button>
      </div>

      {!latestInsight ? (
        <div className="text-sm opacity-60 font-sans py-4">No AI analysis available for this candidate yet.</div>
      ) : (
        <div className="space-y-4 font-sans text-sm text-ink">
          {latestInsight.content.summary && (
            <div>
              <strong className="block uppercase tracking-wider text-xs mb-1">Executive Summary</strong>
              <p className="opacity-80">{latestInsight.content.summary}</p>
            </div>
          )}
          
          <div className="grid md:grid-cols-2 gap-6 mt-4">
            {latestInsight.content.strengths && (
              <div>
                <strong className="block uppercase tracking-wider text-xs mb-2">Key Strengths</strong>
                <ul className="list-disc pl-4 space-y-1 opacity-80">
                  {latestInsight.content.strengths.map((s, i) => <li key={i}>{s}</li>)}
                </ul>
              </div>
            )}
            
            {latestInsight.content.weaknesses && (
              <div>
                <strong className="block uppercase tracking-wider text-xs mb-2">Key Weaknesses</strong>
                <ul className="list-disc pl-4 space-y-1 opacity-80">
                  {latestInsight.content.weaknesses.map((w, i) => <li key={i}>{w}</li>)}
                </ul>
              </div>
            )}
          </div>
          <div className="text-xs opacity-40 mt-4 pt-2 border-t border-rule text-right">
            Generated by {latestInsight.model_used} on {new Date(latestInsight.created_at).toLocaleDateString()}
          </div>
        </div>
      )}
    </div>
  );
}
